language: python

python:
- 3.4
- 3.5
- 3.6

before_install:
- pip install numpy
- pip install sympy

install:
- python setup.py build install

script:
- pytest

notifications:
        webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
        email: false
